// <auto-generated />
using System;
using FoodProcessorShop.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodProcessorShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodProcessorShop.Models.FoodProcessor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BowlCapacity")
                        .HasColumnType("double precision");

                    b.Property<string>("BowlMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FoodProcessors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b17ddd4a-b7ae-4bde-a25d-dba74c6ab5f3"),
                            BowlCapacity = 0.34999999999999998,
                            BowlMaterial = "Пластик",
                            Company = "Aresa",
                            Name = "AR-1704",
                            Price = 2399,
                            SpeedsCount = 1
                        },
                        new
                        {
                            Id = new Guid("3875e3fb-2def-42a5-ac94-f904569c7eb7"),
                            BowlCapacity = 4.0,
                            BowlMaterial = "Металл",
                            Company = "Endever",
                            Name = "Sigma-21S",
                            Price = 6099,
                            SpeedsCount = 6
                        });
                });

            modelBuilder.Entity("FoodProcessorShop.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FoodProcessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isUrgently")
                        .HasColumnType("boolean");

                    b.HasKey("OrderId");

                    b.HasIndex("FoodProcessorId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodProcessorShop.Models.Order", b =>
                {
                    b.HasOne("FoodProcessorShop.Models.FoodProcessor", "FoodProcessor")
                        .WithMany()
                        .HasForeignKey("FoodProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodProcessor");
                });
#pragma warning restore 612, 618
        }
    }
}
